[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://paneura-api.onrender.com/api/clients"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 